// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var parseDecimals, parseNumber, plural, rubles, toFloat, words;

  words = [['', 'один', 'два', 'три', 'четыре', 'пять', 'шесть', 'семь', 'восемь', 'девять', 'десять', 'одиннадцать', 'двенадцать', 'тринадцать', 'четырнадцать', 'пятнадцать', 'шестнадцать', 'семнадцать', 'восемнадцать', 'девятнадцать'], ['', '', 'двадцать', 'тридцать', 'сорок', 'пятьдесят', 'шестьдесят', 'семьдесят', 'восемьдесят', 'девяносто'], ['', 'сто', 'двести', 'триста', 'четыреста', 'пятьсот', 'шестьсот', 'семьсот', 'восемьсот', 'девятьсот']];

  toFloat = function(number) {
    return parseFloat(number);
  };

  plural = function(count, options) {
    var rest;

    if (options.length !== 3) {
      return false;
    }
    count = Math.abs(count) % 100;
    rest = count % 10;
    if (count > 10 && count < 20) {
      return options[2];
    }
    if (rest > 1 && rest < 5) {
      return options[1];
    }
    if (rest === 1) {
      return options[0];
    }
    return options[2];
  };

  parseNumber = function(number, count) {
    var first, numeral, second;

    numeral = '';
    if (number.length === 3) {
      first = number.substr(0, 1);
      number = number.substr(1, 3);
      numeral = "" + words[2][first] + " ";
    }
    if (number < 20) {
      numeral += "" + words[0][toFloat(number)] + " ";
    } else {
      first = number.substr(0, 1);
      second = number.substr(1, 2);
      numeral += "" + words[1][first] + " " + words[0][second] + " ";
    }
    switch (count) {
      case 0:
        numeral += plural(number, ['рубль', 'рубля', 'рублей']);
        break;
      case 1:
        numeral += plural(number, ['тысяча ', 'тысячи ', 'тысяч ']);
        numeral = numeral.replace('один ', 'одна '.replace('два ', 'две '));
        break;
      case 2:
        numeral += plural(number, ['миллион ', 'миллиона ', 'миллионов ']);
        break;
      case 3:
        numeral += plural(number, ['миллиард ', 'миллиарда ', 'миллиардов ']);
    }
    return numeral;
  };

  parseDecimals = function(number) {
    var text;

    text = plural(number, ['копейка', 'копейки', 'копеек']);
    if (number === 0) {
      number = '00';
    }
    return " " + number + " " + text;
  };

  rubles = function(number) {
    var count, decimals, digit, length, numeral, parts, _ref;

    if (!number || number === 0) {
      return false;
    }
    if (typeof number !== 'number') {
      number = toFloat(number.replace(',', '.'));
      if (isNaN(number)) {
        return false;
      }
    }
    number = number.toFixed(2);
    if (number.indexOf('.') !== -1) {
      _ref = number.split('.'), number = _ref[0], decimals = _ref[1];
    }
    numeral = '';
    length = number.length - 1;
    parts = '';
    count = 0;
    while (length >= 0) {
      digit = number.substr(length, 1);
      parts = digit + parts;
      if ((parts.length === 3 || length === 0) && !isNaN(toFloat(parts))) {
        numeral = parseNumber(parts, count) + numeral;
        parts = '';
        count++;
      }
      length--;
    }
    numeral = numeral.replace('  ', ' ');
    if (decimals) {
      numeral += parseDecimals(toFloat(decimals));
    }
    return numeral;
  };

  (exports || window).rubles = rubles;

}).call(this);
